#Remap Prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

#Split CMDs
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

#Reload
bind r source-file ~/.tmux.conf

#Arrow Move
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

#Mouse Option
set -g mouse on

#No Auto Rename
set-option -g allow-rename off


